@startuml
!include <C4/C4_Context>

title Уровень Context

LAYOUT_LEFT_RIGHT()

Person(user, "User", "Тренирующийся, пользователь системы")
System(system, "Training System", "Программный комплекс составления программ спортивных тренировок")

Rel(user, system, "Работает с тренировками")

SHOW_LEGEND()
@enduml