{
 "title": "Gateway",
 "tags": [
  "application",
  "gateway",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Средняя длительность запроса",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(gateway_request_sum[$__rate_interval]) / rate(gateway_request_count[$__rate_interval])",
     "legendFormat": "Средняя длительность"
    }
   ]
  },
  {
   "title": "Кол-во запросов по коду ответа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (increase(gateway_request_count[$__range]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Кол-во ошибок сервиса",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(gateway_error_total[$__range]) or vector(0)",
     "legendFormat": "Ошибки"
    }
   ]
  }
 ]
}